--- #YAML:1.0
name:               Kook
version:            0.0100
abstract:           task automation utility like Make, Rake, or Ant
author:
    - makoto kuwata <kwa(at)kuwata-lab.com>
license:            MIT-License
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Oktest:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
